deployment:
  name: devops-api
  replicas: 3
  repository:
    image: ulan025/node-api
    tag: 1.0.0
  containerPort: 3001

service:
  name: devops-api
  port: 3001
  targetPort: 3001
  type: LoadBalancer